# -*- coding: utf-8 -*-
"""PER 5. Program Hierarchical inheritance. 3

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qCEfbWnIx7YSmtOF7HtAnittDtST06Sk
"""

#Class parent
class Induk:
  def fungsiinduk(self):
    print('Fungsi pada perent class')

#Class turunan 1
class Anak1(Induk):
  def fungsianak1(self):
    print('FUNGSI PADA ANAK 1')

#Class turunan 2
class Anak2(Induk):
  def fungsianak2(self):
    print('FUNGSI PADA ANAK 2')

#objek
a1 = Anak1()
a2 = Anak2()

a1.fungsiinduk()
a1.fungsianak1()
a2.fungsiinduk()
a2.fungsianak2()