# -*- coding: utf-8 -*-
"""PER 5. Program Class ComputerPart. 5

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qCEfbWnIx7YSmtOF7HtAnittDtST06Sk
"""

class ComputerPart:
    def _init_(self, pabrikan, nama, jenis, harga) :
        self.pabrikan = pabrikan
        self.nama = nama
        self.jenis = jenis
        self.harga = harga

class Processor(ComputerPart) :
    def _init_(self, pabrikan, nama, harga, jumlah_core, speed) :
        super()._init_(pabrikan, nama, 'processor', harga)
        self.jumlah_core = jumlah_core
        self.speed = speed

class RandomAccessMemory(ComputerPart) :
    def _init_(self, pabrikan, nama, harga, kapasitas) :
        super()._init_(pabrikan, nama, 'SATA', harga)
        self.kapasitas = kapasitas
    
class HardDiskSATA(ComputerPart) :
    def _init_(self, pabrikan, nama, harga, kapasitas, rpm) :
        super()._init_(pabrikan, nama, 'SATA', harga)
        self.kapasitas = kapasitas
        self.rpm = rpm 

p = Processor('Intel', 'Core i7 7740X', 4350000, 4, '4.3GHz')
m = RandomAccessMemory('V-Gen', 'DDR4 SODimm PC19200/2400MHz', 328000, '4GB')
hdd = HardDiskSATA('Seagate', 'HDD 2.5 inch', 295000, '500GB', 7200)

parts = [p, m, hdd]
for part in parts :
    print('{} {} produksi {}'.format(part.jenis, part.nama, part.pabrikan))