# -*- coding: utf-8 -*-
"""PER 5. Program Multiple inheritance. 4

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qCEfbWnIx7YSmtOF7HtAnittDtST06Sk
"""

#Parent 1
class Perhitungan1:
  def penjumlahan(self,a,b):
    return a+b

#Parent 2
class Perhitungan2:
  def perkalian(self,a,b):
    return a*b

#Child
class Hitung(Perhitungan1, Perhitungan2):
  def pembagian(self,a,b):
    return a/b

h = Hitung()
print(h.penjumlahan(20,30))
print(h.perkalian(5,4))
print(h.pembagian(6,12))